### ISSUE TITLE
Header links reload the whole page instead of just navigating to the right place

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/obsidian-zola-plus#14]

**Comment by posercorpse** [comment]
Would this perhaps be the cause of the graph loading unconnected/ghost nodes when clicking on a header in the TOC panel?

**Comment by Yarden-zamir** [comment]
No, that would be because the graph is based on the url and when clicking on a header it adds #header to the url. Can probably think of a workaround, maybe open a seperate issue and we can investigate

**Comment by orditeck** [comment]
Fix here: https://github.com/orditeck/obsidian-zola-plus/commit/a4d07cdb86a7c06b20a832cb9da7bdf562ae85da?diff=unified

**Comment by Yarden-zamir** [comment]
@orditeck Thank you! I belive your repo is privete though

**Comment by orditeck** [comment]
> @orditeck Thank you! I belive your repo is privete though

Oops, my bad, I fixed the link.

> Can you make a pr?

Done.
